apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-onerror
  namespace: tektutor
spec:
  steps:
  - name: step1-with-error
    image: docker.io/library/golang:latest
    onError: continue
    script: |
            go test .

  - name: step2-after-erro
    image: ubuntu
    command:
      - echo "Inspite of step had reported an error, this step2 executed !"
