apiVersion: v1
kind: Secret
metadata:
  name: mysql-login-credentials 
type: Opaque
data:
  adminUsername: cm9vdAo= 
  adminPassword: cm9vdEAxMjMK 
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: task-with-secrets 
spec:
  workspaces:
    - name: mysql-credentials 
      secret:
        secretName: mysql-login-credentials 
        items:
          - key: adminUsername 
            path: adminUser.txt
          - key: adminPassword
            path: adminPassword.txt
  taskSpec:
    steps:
    - name: reads-mysql-login-crentials
      image: ubuntu
      script: cat $(workspaces.mysql-credentials.path)/adminUser.txt && cat $(workspaces.mysql-credentials.path)/adminPassword.txt
    workspaces:
    - name: mysql-credentials 
      mountPath: /my/secrets
