apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    server: "192.168.1.80"
    path: "/mnt/nfs_share"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: task-with-persistentvolume
spec:
  workspaces:
    - name: myworkspace 
      persistentVolumeClaim:
        claimName: my-pvc
  taskSpec:
    steps:
    - name: store-myworkspace-path 
      image: ubuntu
      script: echo $(workspaces.myworkspace.path) > $(workspaces.myworkspace.path)/path
    - name: read-path
      image: ubuntu
      script: cat $(workspaces.myworkspace.path)/path
    workspaces:
    - name: myworkspace
      mountPath: /my/myworkspace
