apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - name: wordpress
      port: 8080
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
